name: Compile and Distribute HeHeSPY Executables

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Create directory for compiled executables
        run: mkdir dist

      - name: Find and compile Python executables
        run: |
          Get-ChildItem -Filter *.py | ForEach-Object {
            $script = $_.FullName
            Write-Output "Compiling $script"
            python -m pyinstaller --onefile $script --distpath dist
          }


      - name: Archive compiled executables
        uses: actions/upload-artifact@v2
        with:
          name: compiled-scripts
          path: dist
