name: Compile and Distribute HeHeSPY executables

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Create directory for compiled executables
        run: mkdir -p dist

      - name: Find and compile Python executables
        run: |
          for file in $(find . -name '*.py'); do
            echo "Compiling $file"
            script_name=$(basename "${file%.*}")
            python -m pyinstaller --onefile "$file"
          done

      - name: Archive compiled executables
        uses: actions/upload-artifact@v2
        with:
          name: compiled-scripts
          path: dist
