name: Compile and Distribute HeHeSPY Executables

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        shell: cmd
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Verify pyinstaller installation
        shell: cmd
        run: |
          python -m pip show pyinstaller

      - name: Create directory for compiled executables
        shell: cmd
        run: mkdir dist

      - name: Find and compile Python executables
        shell: cmd
        run: |
          for %%f in (*.py) do (
            echo Compiling %%f
            C:\hostedtoolcache\windows\Python\3.11.9\x64\python.exe -m pyinstaller --onefile "%%f" --distpath dist
          )

      - name: Archive compiled executables
        shell: cmd
        run: |
          robocopy dist $(Build.ArtifactStagingDirectory)\dist /E /NFL /NDL /NJH /NJS
          echo ##vso[task.uploadfile]$(Build.ArtifactStagingDirectory)\dist

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: compiled-scripts
          path: $(Build.ArtifactStagingDirectory)\dist
