name: Compile and Distribute Python Scripts

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11' # Specify your desired Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install nuitka

      - name: Create directory for compiled scripts
        run: mkdir -p compiled_scripts

      - name: Find and compile Python scripts
        run: |
          for file in $(find . -name '*.py'); do
            echo "Compiling $file"
            script_name=$(basename "${file%.*}")
            nuitka --onefile --output-dir=compiled_scripts "$file"
          done

      - name: Archive compiled scripts
        uses: actions/upload-artifact@v2
        with:
          name: compiled-scripts
          path: compiled_scripts
